[versions]
androidx-activity-activity-compose-version = "1.8.2"
androidx-compose-compose-bom-version = "2024.02.02"
androidx-compose-material3-material3-version = "1.2.1"
androidx-datatore-datatore-preferences-version = "1.0.0"
androidx-hilt-hilt-navigation-compose-version = "1.2.0"
androidx-kotlin-compose-compiler-version = "1.5.9"
androidx-lifecycle-version = "2.7.0"
androidx-navigation-navigation-compose-version = "2.7.7"
androidx-test-core-version = "1.5.0"
androidx-test-ext-junit-version = "1.1.5"
androidx-test-ext-junit-ktx-version = "1.1.5"
androidx-test-rules-version = "1.5.0"
androidx-test-runner-version = "1.5.2"
app-cash-turbine-turbine-version = "1.1.0"
com-android-tools-build-gradle-version = "8.3.0"
com-android-tools-desugar-jdk-libs-version = "2.0.4"
com-jakewharton-timber-timber-version = "5.0.1"
com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter-version = "1.0.0"
com-google-android-libraries-mapsplatform-secrets-gradle-plugin-version = "2.0.1"
com-google-dagger-hilt-android-version = "2.51"
com-squareup-okhttp3-logging-interceptor-version = "4.12.0"
com-squareup-retrofit2-retrofit-version = "2.10.0"
dev-forkhandles-result4k-version = "2.14.0.0"
io-coil-kt-version = "2.6.0"
io-strikt-strikt-core-version = "0.34.1"
junit-junit-version = "4.13.2"
org-jetbrains-kotlin-version = "1.9.22"
org-jetbrains-kotlinx-kotlinx-collections-immutable-version = "0.3.7"
org-jetbrains-kotlinx-kotlinx-coroutines-version = "1.8.0"
org-jetbrains-kotlinx-kotlinx-serialization-json-version = "1.6.3"
org-junit-junit-bom-version = "5.10.2"

[libraries]
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-activity-compose-version" }
androidx-compose-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-compose-bom-version" }
androidx-compose-material-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3-material3-version" }
androidx-compose-runtime-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-datastore-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datatore-datatore-preferences-version" }
androidx-hilt-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt-hilt-navigation-compose-version" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit-version" }
androidx-lifecycle-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-version" }
androidx-lifecycle-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-version" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-version" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-navigation-compose-version" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core-version" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext-junit-ktx-version" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules-version" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner-version" }
app-cash-turbine-turbine = { module = "app.cash.turbine:turbine", version.ref = "app-cash-turbine-turbine-version" }
com-android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "com-android-tools-build-gradle-version" }
com-android-tools-desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "com-android-tools-desugar-jdk-libs-version" }
com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "com-jakewharton-retrofit-retrofit2-kotlinx-serialization-converter-version" }
com-jakewharton-timber-timber = { module = "com.jakewharton.timber:timber", version.ref = "com-jakewharton-timber-timber-version" }
com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "com-google-dagger-hilt-android-version" }
com-google-dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "com-google-dagger-hilt-android-version" }
com-google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "com-google-dagger-hilt-android-version" }
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3-logging-interceptor-version" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2-retrofit-version" }
dev-forkhandles-result4k = { module = "dev.forkhandles:result4k", version.ref = "dev-forkhandles-result4k-version" }
io-coil-kt = { module = "io.coil-kt:coil", version.ref = "io-coil-kt-version" }
io-coil-kt-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "io-coil-kt-version" }
io-strikt-strikt-core = { module = "io.strikt:strikt-core", version.ref = "io-strikt-strikt-core-version" }
junit-junit = { module = "junit:junit", version.ref = "junit-junit-version" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin-version" }
org-jetbrains-kotlinx-kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "org-jetbrains-kotlinx-kotlinx-collections-immutable-version" }
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx-kotlinx-coroutines-version" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx-kotlinx-coroutines-version" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx-kotlinx-coroutines-version" }
org-jetbrains-kotlinx-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "org-jetbrains-kotlinx-kotlinx-serialization-json-version" }
org-junit-junit-bom = { module = "org.junit:junit-bom", version.ref = "org-junit-junit-bom-version" }
org-junit-jupiter-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
org-junit-vintage-junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-tools-build-gradle-version" }
com-android-library = { id = "com.android.library", version.ref = "com-android-tools-build-gradle-version" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "com-google-dagger-hilt-android-version" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-version" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "org-jetbrains-kotlin-version" }
com-google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "com-google-android-libraries-mapsplatform-secrets-gradle-plugin-version" }

[bundles]
android-test = [
    "junit-junit",
    "org-junit-jupiter-junit-jupiter",
    "androidx-compose-ui-ui-test-junit4",
    "androidx-test-core",
    "androidx-test-rules",
    "androidx-test-runner",
    "com-google-dagger-hilt-android-testing",
    "androidx-test-ext-junit"
]
compose = [
    "androidx-compose-material-material-icons-extended",
    "androidx-compose-material3-material3",
    "androidx-compose-runtime-runtime",
    "androidx-compose-ui-ui",
    "androidx-compose-ui-ui-tooling-preview",
    "androidx-compose-ui-ui-util",
    "androidx-lifecycle-lifecycle-runtime-compose",
]
coroutines = [
    "org-jetbrains-kotlinx-kotlinx-coroutines-android",
    "org-jetbrains-kotlinx-kotlinx-coroutines-core",
]
test = [
    "org-junit-jupiter-junit-jupiter",
    "io-strikt-strikt-core",
    "org-jetbrains-kotlinx-kotlinx-coroutines-test",
    "app-cash-turbine-turbine",
]
