name: Build

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: build-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 45

        steps:
            -   uses: actions/checkout@v4

            -   name: Validate Gradle Wrapper
                uses: gradle/wrapper-validation-action@v2

            -   name: set up JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   uses: gradle/gradle-build-action@v3
                with:
                    gradle-home-cache-cleanup: true

            -   name: Apply formatting if failed
                run: ./gradlew spotlessApply --init-script gradle/init.gradle.kts --no-configuration-cache
            -   uses: stefanzweifel/git-auto-commit-action@v5
                with:
                    commit_message: Apply Spotless

            -   name: Check lint
                run: ./gradlew lintDebug

            -   name: Build
                run: ./gradlew assembleDebug

            -   name: Run tests
                run: ./gradlew test

            -   name: Run check
                run: ./gradlew check
